[package]
name = "count-newlines"
version = "0.2.0"
edition = "2024"
license = "Apache-2.0"
description = "A simple SIMD-enabled newline counter"
repository = "https://github.com/jjl/co[unt-newlines"
docs = "https://docs.rs/count-newlines"
[dependencies]
